server:
  port: 8888


spring:
  application:
    name: config-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


  profiles:
    active: git


  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/coding/msa/e-commerce/git-local-repo
        git:
          uri: https://github.com/dong-junn/spring_cloud_study_e-commerce-config.git
          default-label: main  # GitHub 기본 브랜치가 main인 경우


management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
